# Generated by Django 3.0.4 on 2020-04-02 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('goal', models.CharField(default='', max_length=2000)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(default=datetime.datetime(2020, 4, 30, 16, 54, 46, 886910))),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Anonymous', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('email_address', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=10000)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('website_url', models.CharField(default='', max_length=200)),
                ('organization_email_address', models.CharField(default='', max_length=200)),
                ('organization_phone_number', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('offer_description', models.CharField(default='', max_length=10000)),
                ('offer', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('website_url', models.CharField(default='', max_length=200)),
                ('business_email_address', models.CharField(default='', max_length=200)),
                ('business_phone_number', models.CharField(default='', max_length=20)),
                ('is_offer_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('goal', models.CharField(default='', max_length=2000)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorSponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sponsor', verbose_name='the related sponsor')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sponsorship', verbose_name='the related sponsorship')),
            ],
        ),
        migrations.CreateModel(
            name='DonorDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Donation', verbose_name='the related donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Donor', verbose_name='the related donor')),
            ],
        ),
    ]
