# Generated by Django 3.0.5 on 2020-04-09 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 53, 41, 932384)),
        ),
    ]
