# Generated by Django 2.2.4 on 2020-04-09 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200408_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 5, 32, 59, 46568)),
        ),
    ]
